### PR TITLE
Add php 7.4

### PR DESCRIPTION
**Pull request by rwaffen**

### CODE REVIEW

**Comment by rwaffen** [comment]
I don't know how to fix this. The CI seems to have some Dependency issues...

```
ERROR:  Error installing rubygems-update:
	There are no versions of rubygems-update (= 3.0.6) compatible with your Ruby & RubyGems
	rubygems-update requires Ruby version >= 2.3.0. The current ruby version is 2.1.0.
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /home/travis/.rvm/gems/ruby-2.1.9/gems/rubygems-update-2.7.8
```

**Comment by a3mar** [comment]
Try build again please, this bug in rubygems https://github.com/rubygems/rubygems/pull/3040 was fixed in 3.1.2 version

**Comment by siebrand** [comment]
Any chance of getting this added any time soon? I can confirm this code allows installing PHP 7.4.

**Comment by rwaffen** [comment]
oh, totally forgot about this. we kept using our fork. how can i trigger a rebuild?

**Comment by siebrand** [comment]
Still no progress here. Is this module unmaintained?

**Comment by yakatz** [comment]
That was my guess. We have stopped using it in favor of directly using yumrepo and package. Maybe voxpupuli is interested in hosting it. I can ask.

**Pull request closed without merging**
